name: Test GitHub Actions

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: false
        default: 'Testing GitHub Actions'

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print message
        run: |
          echo "GitHub Actions is working!"
          echo "Message: ${{ github.event.inputs.message }}"
      
      - name: Get version info
        run: |
          echo "Current version in package.json: $(node -p "require('./package.json').version")"
